### ISSUE TITLE
Optimize Disconnect Logic of Libp2p

### ISSUE THREAD

**Issue by 317787106** [tronprotocol/libp2p#60]
# Rationale

## 1. Disconnect logic

When libp2p fails to process the peer's message or when a specific business logic is triggered actively, it will disconnect with a particular peer, namely close the channel at once without notifying the peer of the reason for the disconnection. This is very unfriendly to analyze problems for peers. This article analyzes the disconnection logic in libp2p and java-tron and then tries to send a disconnect message to the peer before disconnecting the peer so that optimizes the user experience.

## 2. Scene analysis of disconnection

We analyzed the disconnection scenario as follows:
![image](https://github.com/tronprotocol/libp2p/assets/23312631/667d2e4e-b333-4ab4-9129-b6c2fb1d6706)

when libp2p disconnects with peers?

Most disconnection happens when P2pException occurs, the red part marks the case where the TypeEnum of P2pException is not specified. We add a disconnect message, which sends a TCP message before the channel is actually disconnected.

# Implementation

## 1. Define DisconnectReason

Append the following types to protos/Connect.proto of libp2p:

    enum DisconnectReason {
      PEER_QUITING = 0x00;
      BAD_PROTOCOL = 0x01;
      TOO_MANY_PEERS = 0x02;
      DUPLICATE_PEER = 0x03;
      DIFFERENT_VERSION = 0x04;
      RANDOM_ELIMINATION = 0x05;
      EMPTY_MESSAGE = 0X06;
      PING_TIMEOUT = 0x07;
      DISCOVER_MODE = 0x08;
      DETECT_COMPLETE = 0x09;
      NO_SUCH_MESSAGE = 0x0A;
      BAD_MESSAGE = 0x0B;
      TOO_MANY_PEERS_WITH_SAME_IP = 0x0C;
      RECENT_DISCONNECT = 0x0D;
      DUP_HANDSHAKE = 0x0E;
      UNKNOWN = 0xFF;
    }

    message P2pDisconnectMessage {
      DisconnectReason reason = 1;
    }

Convert the TypeEnum of P2pException to DisconnectReason:

        P2pException pe = (P2pException) e;
        DisconnectReason disconnectReason;
        switch (pe.getType()) {
          case EMPTY_MESSAGE:
            disconnectReason = DisconnectReason.EMPTY_MESSAGE;
            break;
          case BAD_PROTOCOL:
            disconnectReason = DisconnectReason.BAD_PROTOCOL;
            break;
          case NO_SUCH_MESSAGE:
            disconnectReason = DisconnectReason.NO_SUCH_MESSAGE;
            break;
          case BAD_MESSAGE:
          case PARSE_MESSAGE_FAILED:
          case MESSAGE_WITH_WRONG_LENGTH:
          case TYPE_ALREADY_REGISTERED:
            disconnectReason = DisconnectReason.BAD_MESSAGE;
            break;
          default:
            disconnectReason = DisconnectReason.UNKNOWN;
        }

## 2. Send disconnect messages

Before the channel actively disconnects, send TCP P2pDisconnectMessage as much as possible to inform the peer of the disconnection reason:

    channel.send(new P2pDisconnectMessage(disconnectReason));

# Compatibility

For libp2p nodes that do not support P2pDisconnectMessage, a P2pException of NO\_SUCH\_MESSAGE will be thrown after receiving the message, and then the channel will be disconnected as well.

**Comment by wubin01** [comment]
It doesn't make much sense, the disconnection of libp2p is mainly done in handshake.

**Comment by chengtx01** [comment]
> For libp2p nodes that do not support P2pDisconnectMessage, a P2pException of NO_SUCH_MESSAGE will be thrown after receiving the message, and then the channel will be disconnected as well.

@317787106 Are you saying that you don't support version compatibility? Will upgrading some nodes cause network fragmentation?

**Comment by 317787106** [comment]
> > For libp2p nodes that do not support P2pDisconnectMessage, a P2pException of NO_SUCH_MESSAGE will be thrown after receiving the message, and then the channel will be disconnected as well.
> 
> @317787106 Are you saying that you don't support version compatibility? Will upgrading some nodes cause network fragmentation?

Libp2p with older version couldn't parse P2pDisconnectMessage, and still disconnect with other node when receive P2pDisconnectMessage , that's the same logic as ago. This will not cause network fragmentation.
