### ISSUE TITLE
Optimize p2p handshake logic

### ISSUE THREAD

**Issue by ss3344520** [tronprotocol/libp2p#61]
# Rationale
After the handshake is completed, it will be negotiated whether to use message compression to communicate.

There should be no other message exchange before the handshake is completed, which may cause message parsing failure and disconnection.

<img width="411" alt="image" src="https://github.com/tronprotocol/java-tron/assets/37210306/b895234d-d2ea-4bde-af0a-6b08544ffde0">

### Background
After the TCP connection is established, if there is a network jitter, the handshake time may exceed 20s. At this time, the channel keep-alive function will be triggered and a ping message will be sent. Since the handshake is not completed, the ping packet sent at this time is an uncompressed packet. If the handshake result is communicated in a compressed way, the uncompressed message will fail to parse and the connection will be disconnected.

<img width="448" alt="image" src="https://github.com/tronprotocol/java-tron/assets/37210306/abef5ca8-cef9-4c47-a526-1b61d829ddd3">

# Implementation
For the current version release_v4.7.2, after the TCP connection is established, there should be no packet or message exchange until the p2p handshake is completed except for the channel keep-alive message. So the ping message should be sent after the handshake is completed, otherwise, disconnection may be incurred.

**Comment by 317787106** [comment]
Have you simulate this case that send ping before finishing handashake in realtime ? What's the possibility ?

**Comment by ss3344520** [comment]
Refer to pr https://github.com/tronprotocol/libp2p/pull/65
