### ISSUE TITLE
Optimize thread pool and thread name in Libp2p

### ISSUE THREAD

**Issue by 317787106** [tronprotocol/libp2p#62]
# Rationale

## Background

At present, the libp2p thread name is not clearly defined, and the thread names in the log are confusing. A function may be called by multiple threads; when a problem occurs, it is impossible to quickly find out which task triggered the corresponding log, which is very inconvenient for finding the problem.

## Specification of creating a single thread

Thread resources must be provided through the thread pool, and it is not allowed to explicitly create threads in an application.

Description: The advantage of using the thread pool is to reduce the time spent on creating/killing threads and to reduce the overhead of the system, solving the problem of insufficient resources. If the thread pool is not used, it may cause the system to create a large number of threads of the same type, resulting in memory consumption or "over-switching".

## Specification of creating a thread pool

Thread pools are not allowed to be created using Executors, but through ThreadPoolExecutor. This processing method allows other developers to clarify the running rules of the thread pool and avoid the risk of resource exhaustion.

Description: The disadvantages of each method of Executors:

1.  newFixedThreadPool and newSingleThreadExecutor: the main problem is that the accumulated request processing queue may consume a very large amount of memory or even incurs OOM.
2.  newCachedThreadPool and newScheduledThreadPool: the main problem is that the maximum number of threads is Integer.MAX\_VALUE, which may create a very large number of threads or even incurs OOM.

## Specification of thread’s name

At present, most threads do not specify the thread name related to the logic, so the default thread names are used. If a meaningful thread name is given, it is easy to trace and quickly troubleshoot problems when an exception occurs, comparing the default thread names.

Example: A NioEventLoopGroup thread pool created by java-tron does not specify a thread name, and the default name is nioEventLoopGroup-X-Y:

    18:17:48.177 INFO  [nioEventLoopGroup-6-1] [net](P2pEventHandlerImpl.java:212) Message processing costs 85 ms, peer: /132.145.129.253:14774, type: BLOCK, time tag: ~~
    18:17:48.181 INFO  [nioEventLoopGroup-6-32] [net](P2pEventHandlerImpl.java:167) Receive message from  peer: /45.33.38.111:46800, type: INVENTORY 
    invType: BLOCK, size: 1, First hash: 000000000328fcefa48204c354fbf5caa2483e13c0f61ffa54188fd69aa33003

The meaning of the first serial number X: if there are multiple NioEventLoopGroup thread pools with the default thread name in an application, this represents the serial number of the thread pool, starting from 1.

The meaning of the second serial number Y: the serial number of a thread in a NioEventLoopGroup thread pool, starting from 1.

Analyzing the source code of NioEventLoopGroup, when the thread name format is not specified, the default construction method is as follows:

![image](https://github.com/tronprotocol/libp2p/assets/23312631/b1741765-8614-4a61-98a0-8a0a61a6256b)
Source of "nioEventLoopGroup"

![image](https://github.com/tronprotocol/libp2p/assets/23312631/cf0402a0-feec-40f3-9569-b4043f55ea43)
Source of "nioEventLoopGroup-X-"

The appearance of this thread name in java-tron is very unfriendly to analyzing logs because users would not know which part of the logic created the thread pool.

# Implementation

For the current situation, there are mainly two aspects to improve, including optimizing the logic of creating a thread pool and specifying the thread name related to the scene.

## Optimize the creation logic of the thread pool

Correct example 1: (single thread)

    //org.apache.commons.lang3.concurrent.BasicThreadFactory 
    ScheduledExecutorService executorService = new ScheduledThreadPoolExecutor(1, 
    new BasicThreadFactory.Builder().namingPattern("example-schedule-pool-%d").daemon(true).build());

Correct example 2: (multithreading)

    ThreadFactory namedThreadFactory = new ThreadFactoryBuilder() 
        .setNameFormat("demo-pool-%d").build(); 
    //Generic thread pool
    ExecutorService pool = new ThreadPoolExecutor(5, 200,
    0L, TimeUnit.MILLISECONDS,
    new LinkedBlockingQueue(1024), namedThreadFactory, new ThreadPoolExecutor.AbortPolicy());
    pool.execute(()-> System.out.println(Thread.currentThread().getName()));
    pool.shutdown();//gracefully shutdown

Correct example 3:

    // Please introduce a thread factory object with factory name already set

    //in code
    userThreadPool.execute(thread); 

## Specify the thread‘s name related to the scene

For a single-threaded thread pool, use the format .namingPattern("example-schedule-pool"); for a multi-threaded thread pool, use the format .namingPattern("example-schedule-pool-%d"). The first letter of all custom thread names should be lowercase uniformly.

**Comment by chengtx01** [comment]
>  it may cause the system to create a large number of threads of the same type

@317787106 I have some questions: why is it not allowed to explicitly create threads in an application? Why does creating threads on demand lead to creating a large number of threads of the same type?

**Comment by 317787106** [comment]
> > it may cause the system to create a large number of threads of the same type
> 
> @317787106 I have some questions: why is it not allowed to explicitly create threads in an application? Why does creating threads on demand lead to creating a large number of threads of the same type?

@chengtx01 The advantage of using the thread pool is to reduce the time spent on creating/killing threads and to reduce the overhead of the system, solving the problem of insufficient resources. If the thread pool is not used, it may cause the system to create a large number of threads of the same type, resulting in memory consumption or "over-switching".

**Comment by lxcmyf** [comment]
@317787106 
Do you define some enumerations to classify the names of various business threads? Perhaps each business can be divided into several subcategories, and the creation method of thread pools also needs to be standardized. The corresponding thread pools for each business need to be designed in place.

**Comment by 317787106** [comment]
> 

Generally, each business can specify thread‘s name freely, there are not these enumerations. May be it's very necessaty to impose strict restrictions.
